version: "3.7"
services:
  nginx:
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet
    secrets:
      - registry-cert
      - registry-key
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=https://${GITEA_HOST}/
      - SSH_DOMAIN=${GITEA_HOST}
    volumes:
      - gitea-app:/data
    ports:
      #- "3000"
      - "22:22"
    networks:
      - appnet

  drone-server:
    image: drone/drone:latest
    ports:
      - 8080:8080
    volumes:
      - drone:/var/lib/drone
      - drone-data:/data
      - ./.certificates/ca.crt:/etc/ssl/certs/ca-certificates.crt
    depends_on:
      - gitea
    environment:
      - DRONE_LOGS_DEBUG=true
      #- DRONE_LOGS_TEXT=true
      - DRONE_LOGS_PRETTY=true
      #- DRONE_LOGS_COLOR=true
      - DRONE_GITEA_SERVER=https://${GITEA_HOST}
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
      - DRONE_SERVER_HOST=${GITEA_HOST}:8080 # tunnel hostname       
      - DRONE_ADMIN=giles
      - DRONE_SERVER_PROTO=http # tunnel adds https on top
      - DRONE_SERVER_PORT=:8080
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_USER_CREATE=username:giles,admin:true
      - DRONE_AGENTS_ENABLED=true
    networks:
      - appnet

  drone-docker-runner:
    image: drone/drone-runner-docker:1
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=${GITEA_HOST}:8080
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=8
      - DRONE_RUNNER_NAME="docker-runner"
  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_HTTP_TLS_CERTIFICATE="/run/secrets/registry-cert"
      - REGISTRY_HTTP_TLS_KEY="/run/secrets/registry-key"
    networks:
      - appnet
    secrets:
      - registry-cert
      - registry-key


volumes:
  gitea-app:
  gitea-db:
  drone:
  drone-data:
  registry-data:

networks:
  appnet:
    driver: overlay
    #external: true

secrets:
  'registry-cert':
    #file: .secrets/sigyl-registry.crt
    file: .certificates/gitea.crt
  'registry-key':
    #file: .secrets/sigyl-registry.key
    file: .certificates/gitea.key
